'use client';

import { useEffect, useRef, useState } from 'react';
import { useSession } from 'next-auth/react';
import { useTranslations } from 'next-intl';
import { ImagePlus, Music, Video as VideoIcon, FileBox, Loader2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from '@/components/ui/toaster';
import { useWizard } from '../wizard-context';
import { useAuthedFetch } from '@/lib/api/client';
import { uploadEditorMedia } from '@/components/rich-text/editor-media-upload';
import { putWithProgress } from '@/lib/upload/put-with-progress';
import { cn } from '@/lib/utils';

interface InitiateThumb {
  putUrl: string;
  key: string;
  expiresAt: string;
}

interface PreviewMediaItem {
  id: string;
  kind: 'image' | 'video' | 'audio' | '3d';
  key: string;
  viewUrl: string;
  label: string;
  mime?: string;
}

const THUMB_MAX = 8 * 1024 * 1024;

export function StepMedia() {
  const wiz = useWizard();
  const t = useTranslations('publish.media');
  const fetcher = useAuthedFetch();
  const { data: session } = useSession();
  const [uploadingThumb, setUploadingThumb] = useState(false);
  const [thumbProgress, setThumbProgress] = useState<number | null>(null);
  const [uploadingPreview, setUploadingPreview] = useState(false);
  const [previewProgress, setPreviewProgress] = useState<number | null>(null);
  const [localThumbUrl, setLocalThumbUrl] = useState<string | null>(null);
  const thumbInputRef = useRef<HTMLInputElement | null>(null);
  const previewInputRef = useRef<HTMLInputElement | null>(null);
  const [previewKind, setPreviewKind] = useState<'image' | 'video' | 'audio' | '3d' | null>(null);

  useEffect(() => {
    return () => {
      if (localThumbUrl) URL.revokeObjectURL(localThumbUrl);
    };
    // We intentionally don't want to revoke on every render — only on unmount
    // and when we replace the URL ourselves (handled in handleThumb).
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleThumb = async (file: File) => {
    if (file.size > THUMB_MAX) {
      toast.error('Thumbnail too large (max 8 MB).');
      return;
    }
    setUploadingThumb(true);
    setThumbProgress(0);
    const objectUrl = URL.createObjectURL(file);
    const previousLocal = localThumbUrl;
    setLocalThumbUrl(objectUrl);
    if (previousLocal) URL.revokeObjectURL(previousLocal);
    try {
      const initiate = await fetcher<InitiateThumb>('/files/thumbnails/initiate', {
        method: 'POST',
        body: {
          assetId: wiz.asset.id,
          contentType: file.type || 'image/png',
          bytes: file.size,
        },
      });
      await putWithProgress({
        url: initiate.putUrl,
        body: file,
        contentType: file.type || 'image/png',
        onProgress: (loaded, total) =>
          setThumbProgress(total ? Math.min(100, Math.round((loaded / total) * 100)) : null),
      });
      await fetcher('/files/thumbnails/complete', {
        method: 'POST',
        body: { assetId: wiz.asset.id, key: initiate.key },
      });
      await wiz.refresh();
    } catch (err) {
      toast.error('Thumbnail upload failed', {
        description: err instanceof Error ? err.message : String(err),
      });
      setLocalThumbUrl(null);
      URL.revokeObjectURL(objectUrl);
    } finally {
      setUploadingThumb(false);
      setThumbProgress(null);
    }
  };

  const handlePreviewMedia = async (file: File) => {
    setUploadingPreview(true);
    setPreviewProgress(0);
    try {
      const { viewUrl, key } = await uploadEditorMedia(file, session?.accessToken, {
        onProgress: (loaded, total) =>
          setPreviewProgress(total ? Math.min(100, Math.round((loaded / total) * 100)) : null),
      });
      const next = [
        ...(((wiz.asset as unknown as { previewMedia?: PreviewMediaItem[] }).previewMedia) ?? []),
        {
          id: cryptoRandomId(),
          kind: previewKind ?? 'image',
          key,
          viewUrl,
          label: file.name,
          mime: file.type,
        },
      ];
      wiz.patch({ previewMedia: next });
    } catch (err) {
      toast.error('Upload failed', {
        description: err instanceof Error ? err.message : String(err),
      });
    } finally {
      setUploadingPreview(false);
      setPreviewProgress(null);
      setPreviewKind(null);
    }
  };

  const previewMedia: PreviewMediaItem[] =
    ((wiz.asset as unknown as { previewMedia?: PreviewMediaItem[] }).previewMedia) ?? [];

  const removePreview = (id: string) => {
    wiz.patch({ previewMedia: previewMedia.filter((m) => m.id !== id) });
  };

  // Prefer the server thumbnail once it's available; fall back to the
  // optimistic blob: URL we created from the picked file so the preview
  // appears immediately, then the auto-generated 3D thumb as a last resort.
  const thumbUrl =
    wiz.asset.thumbnail.url ?? localThumbUrl ?? wiz.asset.thumbnailAutoGenerated?.url ?? null;

  return (
    <div className="space-y-10 max-w-[760px]">
      <section>
        <h2 className="font-display text-h2 text-ink tracking-[-0.01em] mb-2">
          {t('thumbnailTitle')}
        </h2>
        <p className="text-body-sm text-ink-3 mb-4">{t('thumbnailHelper')}</p>
        <div className="relative aspect-[16/9] max-w-[640px] rounded-[20px] border border-line overflow-hidden bg-surface-muted">
          {thumbUrl ? (
            <>
              {/* Plain <img> rendered absolutely inside the sized aspect-ratio
                  parent. We bypass next/image here because the publish wizard
                  needs blob: URLs (for the optimistic local preview before the
                  S3 PUT completes) which next/image refuses to load. */}
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={thumbUrl}
                alt="Thumbnail preview"
                className="absolute inset-0 h-full w-full object-cover"
              />
              {uploadingThumb ? (
                <div className="absolute inset-0 bg-ink/55 backdrop-blur-[4px] flex flex-col items-center justify-center text-white gap-3 px-6">
                  <div className="inline-flex items-center gap-2 text-[13px] font-medium">
                    <Loader2 className="h-4 w-4 animate-spin" strokeWidth={2.25} />
                    Uploading{thumbProgress != null ? ` · ${thumbProgress}%` : '…'}
                  </div>
                  <div className="w-full max-w-[260px] h-1.5 rounded-full bg-white/25 overflow-hidden">
                    <div
                      className="h-full bg-white transition-[width] duration-150"
                      style={{ width: `${thumbProgress ?? 0}%` }}
                    />
                  </div>
                </div>
              ) : null}
              <div className="absolute bottom-3 right-3 flex items-center gap-2">
                <Button variant="secondary" size="sm" onClick={() => thumbInputRef.current?.click()}>
                  {t('replace')}
                </Button>
              </div>
            </>
          ) : (
            <button
              type="button"
              onClick={() => thumbInputRef.current?.click()}
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => {
                e.preventDefault();
                const f = e.dataTransfer.files?.[0];
                if (f) void handleThumb(f);
              }}
              className="absolute inset-0 flex flex-col items-center justify-center gap-2 text-ink-3 hover:text-ink hover:bg-surface-muted/40 transition-colors duration-120"
            >
              {uploadingThumb ? (
                <>
                  <Loader2 className="h-6 w-6 animate-spin" strokeWidth={2.25} />
                  <span className="text-[13px] font-medium text-ink">
                    Uploading{thumbProgress != null ? ` · ${thumbProgress}%` : '…'}
                  </span>
                  <div className="w-44 h-1 rounded-full bg-line overflow-hidden">
                    <div
                      className="h-full bg-brand-blue transition-[width] duration-150"
                      style={{ width: `${thumbProgress ?? 0}%` }}
                    />
                  </div>
                </>
              ) : (
                <>
                  <ImagePlus className="h-6 w-6" strokeWidth={2.25} />
                  <span className="text-[14px] font-medium">{t('thumbnailDrop')}</span>
                </>
              )}
            </button>
          )}
        </div>
        <input
          ref={thumbInputRef}
          type="file"
          hidden
          accept="image/png,image/jpeg,image/webp"
          onChange={(e) => {
            const f = e.currentTarget.files?.[0];
            e.currentTarget.value = '';
            if (f) void handleThumb(f);
          }}
        />
      </section>

      <section>
        <h2 className="font-display text-h2 text-ink tracking-[-0.01em] mb-2">
          {t('previewMediaTitle')}
        </h2>
        <p className="text-body-sm text-ink-3 mb-4">{t('previewMediaHelper')}</p>
        <div className="flex flex-wrap items-center gap-2 mb-4">
          <AddButton
            icon={ImagePlus}
            onClick={() => {
              setPreviewKind('image');
              previewInputRef.current?.click();
            }}
            label={t('addImage')}
          />
          <AddButton
            icon={VideoIcon}
            onClick={() => {
              setPreviewKind('video');
              previewInputRef.current?.click();
            }}
            label={t('addVideo')}
          />
          <AddButton
            icon={Music}
            onClick={() => {
              setPreviewKind('audio');
              previewInputRef.current?.click();
            }}
            label={t('addAudio')}
          />
          <AddButton
            icon={FileBox}
            onClick={() => {
              setPreviewKind('3d');
              previewInputRef.current?.click();
            }}
            label={t('add3d')}
          />
          {uploadingPreview ? (
            <span className="inline-flex items-center gap-2 text-caption text-ink-3">
              <Loader2 className="h-3.5 w-3.5 animate-spin" strokeWidth={2.25} />
              <span>
                {t('uploading')}
                {previewProgress != null ? ` · ${previewProgress}%` : ''}
              </span>
              <span className="w-24 h-1 rounded-full bg-line overflow-hidden align-middle">
                <span
                  className="block h-full bg-brand-blue transition-[width] duration-150"
                  style={{ width: `${previewProgress ?? 0}%` }}
                />
              </span>
            </span>
          ) : null}
        </div>
        <input
          ref={previewInputRef}
          type="file"
          hidden
          accept={
            previewKind === 'image'
              ? 'image/*'
              : previewKind === 'video'
                ? 'video/*'
                : previewKind === 'audio'
                  ? 'audio/*'
                  : previewKind === '3d'
                    ? '.glb,.fbx,.obj'
                    : undefined
          }
          onChange={(e) => {
            const f = e.currentTarget.files?.[0];
            e.currentTarget.value = '';
            if (f) void handlePreviewMedia(f);
          }}
        />
        {previewMedia.length === 0 ? (
          <div className="rounded-[14px] border border-dashed border-line bg-surface-muted/30 p-8 text-center text-body-sm text-ink-3">
            No preview media yet. Use the buttons above to upload images, video, audio, or 3D
            files.
          </div>
        ) : (
          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {previewMedia.map((m) => (
              <PreviewMediaCard key={m.id} item={m} onRemove={() => removePreview(m.id)} />
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}

function PreviewMediaCard({
  item,
  onRemove,
}: {
  item: PreviewMediaItem;
  onRemove: () => void;
}) {
  return (
    <li
      className={cn(
        'relative rounded-[12px] overflow-hidden border border-line bg-surface-muted',
        item.kind === 'audio' ? '' : 'aspect-[16/9]',
      )}
    >
      {item.kind === 'image' ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={item.viewUrl}
          alt={item.label}
          className="absolute inset-0 h-full w-full object-cover"
        />
      ) : item.kind === 'video' ? (
        <video
          src={item.viewUrl}
          controls
          preload="metadata"
          className="absolute inset-0 h-full w-full object-contain bg-ink"
        />
      ) : item.kind === 'audio' ? (
        <div className="p-3 flex flex-col gap-2">
          <div className="inline-flex items-center gap-2 text-caption text-ink-2">
            <Music className="h-4 w-4" strokeWidth={2.25} />
            <span className="font-medium text-ink truncate">{item.label}</span>
          </div>
          <audio src={item.viewUrl} controls preload="metadata" className="w-full" />
        </div>
      ) : (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 text-ink-3 px-4 text-center">
          <FileBox className="h-6 w-6" strokeWidth={2.25} />
          <span className="text-[12.5px] font-medium text-ink truncate max-w-full">
            {item.label}
          </span>
          <span className="text-caption">3D model</span>
        </div>
      )}
      <button
        type="button"
        aria-label="Remove"
        onClick={onRemove}
        className="absolute top-1.5 right-1.5 inline-flex h-7 w-7 items-center justify-center rounded-full bg-white/90 backdrop-blur-[6px] text-ink-2 hover:text-ink shadow-1"
      >
        <X className="h-3.5 w-3.5" strokeWidth={2.25} />
      </button>
      <span className="absolute bottom-1.5 left-1.5 text-[10px] uppercase tracking-[0.1em] text-white bg-ink/65 px-1.5 py-0.5 rounded-[4px]">
        {item.kind}
      </span>
    </li>
  );
}

function AddButton({
  icon: Icon,
  onClick,
  label,
}: {
  icon: typeof ImagePlus;
  onClick: () => void;
  label: string;
}) {
  return (
    <Button
      variant="secondary"
      size="sm"
      onClick={onClick}
      leadingIcon={<Icon className="h-4 w-4" strokeWidth={2.25} />}
    >
      {label}
    </Button>
  );
}

function cryptoRandomId() {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) return crypto.randomUUID();
  return Math.random().toString(36).slice(2);
}
