'use client';

import { useEffect, useRef, useState } from 'react';
import { useSession } from 'next-auth/react';
import { useTranslations } from 'next-intl';
import { ImagePlus, Music, Video as VideoIcon, FileBox, Loader2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ThumbnailImage } from '@/components/asset/thumbnail-image';
import { toast } from '@/components/ui/toaster';
import { useWizard } from '../wizard-context';
import { useAuthedFetch } from '@/lib/api/client';
import { uploadEditorMedia } from '@/components/rich-text/editor-media-upload';
import { cn } from '@/lib/utils';

interface InitiateThumb {
  putUrl: string;
  key: string;
  expiresAt: string;
}

const THUMB_MAX = 8 * 1024 * 1024;

export function StepMedia() {
  const wiz = useWizard();
  const t = useTranslations('publish.media');
  const fetcher = useAuthedFetch();
  const { data: session } = useSession();
  const [uploadingThumb, setUploadingThumb] = useState(false);
  const [uploadingPreview, setUploadingPreview] = useState(false);
  const [localThumbUrl, setLocalThumbUrl] = useState<string | null>(null);
  const thumbInputRef = useRef<HTMLInputElement | null>(null);
  const previewInputRef = useRef<HTMLInputElement | null>(null);
  const [previewKind, setPreviewKind] = useState<'image' | 'video' | 'audio' | '3d' | null>(null);

  useEffect(() => {
    return () => {
      if (localThumbUrl) URL.revokeObjectURL(localThumbUrl);
    };
  }, [localThumbUrl]);

  const handleThumb = async (file: File) => {
    if (file.size > THUMB_MAX) {
      toast.error('Thumbnail too large (max 8 MB).');
      return;
    }
    setUploadingThumb(true);
    const objectUrl = URL.createObjectURL(file);
    // Swap previous local URL — revoke after the new one is in place to avoid flashing empty state.
    const previousLocal = localThumbUrl;
    setLocalThumbUrl(objectUrl);
    if (previousLocal) URL.revokeObjectURL(previousLocal);
    try {
      const initiate = await fetcher<InitiateThumb>('/files/thumbnails/initiate', {
        method: 'POST',
        body: {
          assetId: wiz.asset.id,
          contentType: file.type || 'image/png',
          bytes: file.size,
        },
      });
      await fetch(initiate.putUrl, {
        method: 'PUT',
        headers: { 'Content-Type': file.type || 'image/png' },
        body: file,
      });
      await fetcher('/files/thumbnails/complete', {
        method: 'POST',
        body: { assetId: wiz.asset.id, key: initiate.key },
      });
      await wiz.refresh();
    } catch (err) {
      toast.error('Thumbnail upload failed', {
        description: err instanceof Error ? err.message : String(err),
      });
      // Roll back the optimistic preview if upload failed.
      setLocalThumbUrl(null);
      URL.revokeObjectURL(objectUrl);
    } finally {
      setUploadingThumb(false);
    }
  };

  const handlePreviewMedia = async (file: File) => {
    setUploadingPreview(true);
    try {
      const { viewUrl, key } = await uploadEditorMedia(file, session?.accessToken);
      const next = [
        ...(((wiz.asset as unknown as { previewMedia?: PreviewMediaItem[] }).previewMedia) ?? []),
        {
          id: cryptoRandomId(),
          kind: previewKind ?? 'image',
          key,
          viewUrl,
          label: file.name,
          mime: file.type,
        },
      ];
      wiz.patch({ previewMedia: next });
    } catch (err) {
      toast.error('Upload failed', {
        description: err instanceof Error ? err.message : String(err),
      });
    } finally {
      setUploadingPreview(false);
      setPreviewKind(null);
    }
  };

  const previewMedia: PreviewMediaItem[] =
    ((wiz.asset as unknown as { previewMedia?: PreviewMediaItem[] }).previewMedia) ?? [];

  const removePreview = (id: string) => {
    wiz.patch({ previewMedia: previewMedia.filter((m) => m.id !== id) });
  };

  // Prefer the local optimistic URL until the server-side thumbnail.url shows up,
  // then prefer the server URL so cache-busted variants land correctly.
  const thumbUrl =
    wiz.asset.thumbnail.url ?? localThumbUrl ?? wiz.asset.thumbnailAutoGenerated?.url ?? null;

  return (
    <div className="space-y-10 max-w-[760px]">
      <section>
        <h2 className="font-display text-h2 text-ink tracking-[-0.01em] mb-2">
          {t('thumbnailTitle')}
        </h2>
        <p className="text-body-sm text-ink-3 mb-4">{t('thumbnailHelper')}</p>
        <div className="relative aspect-[16/9] max-w-[640px] rounded-[20px] border border-line overflow-hidden">
          {thumbUrl ? (
            <>
              <ThumbnailImage src={thumbUrl} alt="Thumbnail preview" className="!rounded-[20px]" />
              {uploadingThumb ? (
                <div className="absolute inset-0 bg-ink/40 backdrop-blur-[4px] flex items-center justify-center text-white">
                  <Loader2 className="h-5 w-5 animate-spin" strokeWidth={2.25} />
                </div>
              ) : null}
              <div className="absolute bottom-3 right-3 flex items-center gap-2">
                <Button variant="secondary" size="sm" onClick={() => thumbInputRef.current?.click()}>
                  {t('replace')}
                </Button>
              </div>
            </>
          ) : (
            <button
              type="button"
              onClick={() => thumbInputRef.current?.click()}
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => {
                e.preventDefault();
                const f = e.dataTransfer.files?.[0];
                if (f) void handleThumb(f);
              }}
              className="absolute inset-0 flex flex-col items-center justify-center gap-2 text-ink-3 hover:text-ink hover:bg-surface-muted/40 transition-colors duration-120"
            >
              {uploadingThumb ? (
                <Loader2 className="h-6 w-6 animate-spin" strokeWidth={2.25} />
              ) : (
                <ImagePlus className="h-6 w-6" strokeWidth={2.25} />
              )}
              <span className="text-[14px] font-medium">{t('thumbnailDrop')}</span>
            </button>
          )}
        </div>
        <input
          ref={thumbInputRef}
          type="file"
          hidden
          accept="image/png,image/jpeg,image/webp"
          onChange={(e) => {
            const f = e.currentTarget.files?.[0];
            e.currentTarget.value = '';
            if (f) void handleThumb(f);
          }}
        />
      </section>

      <section>
        <h2 className="font-display text-h2 text-ink tracking-[-0.01em] mb-2">
          {t('previewMediaTitle')}
        </h2>
        <p className="text-body-sm text-ink-3 mb-4">{t('previewMediaHelper')}</p>
        <div className="flex flex-wrap items-center gap-2 mb-4">
          <AddButton icon={ImagePlus} onClick={() => { setPreviewKind('image'); previewInputRef.current?.click(); }} label={t('addImage')} />
          <AddButton icon={VideoIcon} onClick={() => { setPreviewKind('video'); previewInputRef.current?.click(); }} label={t('addVideo')} />
          <AddButton icon={Music} onClick={() => { setPreviewKind('audio'); previewInputRef.current?.click(); }} label={t('addAudio')} />
          <AddButton icon={FileBox} onClick={() => { setPreviewKind('3d'); previewInputRef.current?.click(); }} label={t('add3d')} />
          {uploadingPreview ? (
            <span className="inline-flex items-center gap-1.5 text-caption text-ink-3">
              <Loader2 className="h-3.5 w-3.5 animate-spin" strokeWidth={2.25} />
              {t('uploading')}
            </span>
          ) : null}
        </div>
        <input
          ref={previewInputRef}
          type="file"
          hidden
          accept={
            previewKind === 'image'
              ? 'image/*'
              : previewKind === 'video'
                ? 'video/*'
                : previewKind === 'audio'
                  ? 'audio/*'
                  : previewKind === '3d'
                    ? '.glb,.fbx,.obj'
                    : undefined
          }
          onChange={(e) => {
            const f = e.currentTarget.files?.[0];
            e.currentTarget.value = '';
            if (f) void handlePreviewMedia(f);
          }}
        />
        {previewMedia.length === 0 ? (
          <div className="rounded-[14px] border border-dashed border-line bg-surface-muted/30 p-8 text-center text-body-sm text-ink-3">
            No preview media yet.
          </div>
        ) : (
          <ul className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
            {previewMedia.map((m) => (
              <li
                key={m.id}
                className={cn(
                  'relative aspect-[16/9] rounded-[12px] overflow-hidden border border-line bg-surface-muted',
                )}
              >
                {m.kind === 'image' ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={m.viewUrl} alt={m.label} className="object-cover h-full w-full" />
                ) : (
                  <div className="flex items-center justify-center h-full w-full text-ink-3">
                    {m.kind === 'video' ? (
                      <VideoIcon className="h-5 w-5" strokeWidth={2.25} />
                    ) : m.kind === 'audio' ? (
                      <Music className="h-5 w-5" strokeWidth={2.25} />
                    ) : (
                      <FileBox className="h-5 w-5" strokeWidth={2.25} />
                    )}
                  </div>
                )}
                <button
                  type="button"
                  aria-label="Remove"
                  onClick={() => removePreview(m.id)}
                  className="absolute top-1.5 right-1.5 inline-flex h-7 w-7 items-center justify-center rounded-full bg-white/90 backdrop-blur-[6px] text-ink-2 hover:text-ink"
                >
                  <X className="h-3.5 w-3.5" strokeWidth={2.25} />
                </button>
                <span className="absolute bottom-1.5 left-1.5 right-1.5 truncate text-[10px] uppercase tracking-[0.1em] text-white bg-ink/55 px-1.5 py-0.5 rounded-[4px]">
                  {m.kind}
                </span>
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}

interface PreviewMediaItem {
  id: string;
  kind: 'image' | 'video' | 'audio' | '3d';
  key: string;
  viewUrl: string;
  label: string;
  mime?: string;
}

function AddButton({
  icon: Icon,
  onClick,
  label,
}: {
  icon: typeof ImagePlus;
  onClick: () => void;
  label: string;
}) {
  return (
    <Button variant="secondary" size="sm" onClick={onClick} leadingIcon={<Icon className="h-4 w-4" strokeWidth={2.25} />}>
      {label}
    </Button>
  );
}

function cryptoRandomId() {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) return crypto.randomUUID();
  return Math.random().toString(36).slice(2);
}
